package cn.bnu.model;

// Generated 2018-1-1 17:43:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * NoticeNews generated by hbm2java
 */
public class NoticeNews implements java.io.Serializable {

	private Integer id;
	private String noticeColumn;
	private String noticeTitle;
	private String noticeAuthor;
	private Date publishDate;
	private Date editDate;
	private String noticeContent;
	private Integer noticeState;
	private String attachmentFilename;
	private String description;
	private int readCount;
	private String attachmentFilepath;

	public NoticeNews() {
	}

	public NoticeNews(int readCount) {
		this.readCount = readCount;
	}

	public NoticeNews(String noticeColumn, String noticeTitle,
			String noticeAuthor, Date publishDate, Date editDate,
			String noticeContent, Integer noticeState,
			String attachmentFilename, String description, int readCount,
			String attachmentFilepath) {
		this.noticeColumn = noticeColumn;
		this.noticeTitle = noticeTitle;
		this.noticeAuthor = noticeAuthor;
		this.publishDate = publishDate;
		this.editDate = editDate;
		this.noticeContent = noticeContent;
		this.noticeState = noticeState;
		this.attachmentFilename = attachmentFilename;
		this.description = description;
		this.readCount = readCount;
		this.attachmentFilepath = attachmentFilepath;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNoticeColumn() {
		return this.noticeColumn;
	}

	public void setNoticeColumn(String noticeColumn) {
		this.noticeColumn = noticeColumn;
	}

	public String getNoticeTitle() {
		return this.noticeTitle;
	}

	public void setNoticeTitle(String noticeTitle) {
		this.noticeTitle = noticeTitle;
	}

	public String getNoticeAuthor() {
		return this.noticeAuthor;
	}

	public void setNoticeAuthor(String noticeAuthor) {
		this.noticeAuthor = noticeAuthor;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public Date getEditDate() {
		return this.editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	public String getNoticeContent() {
		return this.noticeContent;
	}

	public void setNoticeContent(String noticeContent) {
		this.noticeContent = noticeContent;
	}

	public Integer getNoticeState() {
		return this.noticeState;
	}

	public void setNoticeState(Integer noticeState) {
		this.noticeState = noticeState;
	}

	public String getAttachmentFilename() {
		return this.attachmentFilename;
	}

	public void setAttachmentFilename(String attachmentFilename) {
		this.attachmentFilename = attachmentFilename;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getReadCount() {
		return this.readCount;
	}

	public void setReadCount(int readCount) {
		this.readCount = readCount;
	}

	public String getAttachmentFilepath() {
		return this.attachmentFilepath;
	}

	public void setAttachmentFilepath(String attachmentFilepath) {
		this.attachmentFilepath = attachmentFilepath;
	}

}
