package cn.bnu.model;

// Generated 2018-1-1 17:43:22 by Hibernate Tools 3.4.0.CR1

/**
 * URoleRight generated by hbm2java
 */
public class URoleRight implements java.io.Serializable {

	private Integer id;
	private String roleId;
	private String rightId;

	public URoleRight() {
	}

	public URoleRight(String roleId, String rightId) {
		this.roleId = roleId;
		this.rightId = rightId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRightId() {
		return this.rightId;
	}

	public void setRightId(String rightId) {
		this.rightId = rightId;
	}

}
