/*
 * File: app/view/achievement_importHisWin.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.achievement_importHisWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.achievement_importHisWin',

    requires: [
        'MyApp.view.achievement_importHisWinViewModel'
    ],

    viewModel: {
        type: 'achievement_importhiswin'
    },
    height: 580,
    html: '<iframe src=\'office/uploadfiles.html\' frameborder=0 width=100% height=100%></iframe>',
    id: 'achievement_importHisWin',
    width: 690,
    layout: 'border',
    title: '历史成果入库'

});