/*
 * File: app/view/achievement_importWin.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.achievement_importWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.achievement_importWin',

    requires: [
        'MyApp.view.achievement_importWinViewModel'
    ],

    viewModel: {
        type: 'achievement_importwin'
    },
    height: 520,
    html: '<iframe src=\'office/supplementfiles.html\' frameborder=0 width=100% height=100%></iframe>',
    id: 'achievement_importWin',
    width: 690,
    title: '上传成果'

});