/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'MyApp.view.MainViewViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.toolbar.Fill',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 90,
            html: '<h1 style="color:#197bc1;;font-family:Microsoft YaHei;margin:10px 0px 0px 35px;"> 系统名称显示',
            itemId: 'headerPanel',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    height: 43,
                    width: 150,
                    items: [
                        {
                            xtype: 'button',
                            id: 'homePanel',
                            text: '主页',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'label',
                            text: '当前时间：'
                        },
                        {
                            xtype: 'label',
                            height: 40,
                            html: '<p id="time">当前时间：</p>',
                            text: '',
                            listeners: {
                                afterrender: 'onLabelAfterRender'
                            }
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'label',
                            text: '当前用户：'
                        },
                        {
                            xtype: 'label',
                            html: '<%=request.getUserPrincipal().getName();%>',
                            id: 'mainview_curUernameLabel',
                            text: 'admin',
                            listeners: {
                                render: 'onMainview_curUernameLabelRender'
                            }
                        },
                        {
                            xtype: 'button',
                            href: 'j_spring_security_logout',
                            hrefTarget: '_parent',
                            text: '退出'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            id: 'mainLeftMenuPanel',
            itemId: 'menuPanel',
            width: 250,
            layout: 'accordion',
            collapseDirection: 'left',
            items: [
                {
                    xtype: 'panel',
                    title: '通知信息管理',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            itemId: 'menu3',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    id: 'notice_Publish',
                                    hideOnClick: false,
                                    text: '通知发布'
                                },
                                {
                                    xtype: 'menuitem',
                                    id: 'notice_Management',
                                    hideOnClick: false,
                                    text: '通知管理'
                                },
                                {
                                    xtype: 'menuitem',
                                    id: 'notice_Columns',
                                    hideOnClick: false,
                                    text: '栏目管理'
                                }
                            ],
                            listeners: {
                                click: 'onMenu3Click4'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: '系统管理维护',
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            itemId: 'menu3',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    id: 'system_UserManage',
                                    hideOnClick: false,
                                    text: '用户信息管理'
                                },
                                {
                                    xtype: 'menuitem',
                                    id: 'system_RightManage',
                                    hideOnClick: false,
                                    text: '角色权限管理'
                                },
                                {
                                    xtype: 'menuitem',
                                    id: 'system_DepartmentManage',
                                    hideOnClick: false,
                                    text: '部门信息管理'
                                },
                                {
                                    xtype: 'menuitem',
                                    hidden: true,
                                    id: 'system_Log',
                                    hideOnClick: false,
                                    text: '系统日志'
                                },
                                {
                                    xtype: 'menuitem',
                                    hidden: true,
                                    id: 'system_DataSearch',
                                    hideOnClick: false,
                                    text: '数据查询'
                                },
                                {
                                    xtype: 'menuitem',
                                    hidden: true,
                                    id: 'system_DataEdit',
                                    hideOnClick: false,
                                    text: '数据编辑'
                                },
                                {
                                    xtype: 'menuitem',
                                    hidden: true,
                                    id: 'system_DataManage',
                                    hideOnClick: false,
                                    text: '数据管理'
                                }
                            ],
                            listeners: {
                                click: 'onMenu3Click8'
                            }
                        }
                    ]
                }
            ],
            listeners: {
                beforerender: 'onMenuPanelBeforeRender'
            }
        },
        {
            xtype: 'panel',
            region: 'center',
            id: 'mainView',
            layout: 'fit'
        }
    ],
    listeners: {
        afterrender: 'onMainViewAfterRender'
    },

    onButtonClick: function(button, e, eOpts) {
        var xtype = button.id;
        var mainView = Ext.getCmp('mainView');
        mainView.removeAll();
        mainView.add(Ext.widget(xtype));
    },

    onLabelAfterRender: function(component, eOpts) {
        document.getElementById('time').innerHTML=new Date().toLocaleString()+' 星期'+'日一二三四五六'.charAt(new Date().getDay());
        setInterval("document.getElementById('time').innerHTML=new Date().toLocaleString()+' 星期'+'日一二三四五六'.charAt(new Date().getDay());",1000);
    },

    onMainview_curUernameLabelRender: function(component, eOpts) {
        Ext.Ajax.request({
            url: 'get_currentUsername',
            success: function(response) {
                var username = response.responseText;
                if (username) {
                    Ext.getCmp('mainview_curUernameLabel').text = username;
                    //component.text = username;
                    //console.log("username:",username);
                } else {
                    //console.log("errorrr.");
                }
            },
            failure: function(conn, response, options, eOpts) {
                console.log("请求错误。");
            }
        });
    },

    onMenu3Click4: function(menu, item, e, eOpts) {
        var xtype = item.id;
        var mainView = Ext.getCmp('mainView');
        mainView.removeAll();
        mainView.add(Ext.widget(xtype));
    },

    onMenu3Click8: function(menu, item, e, eOpts) {
        var xtype = item.id;
        var mainView = Ext.getCmp('mainView');
        mainView.removeAll();
        mainView.add(Ext.widget(xtype));
    },

    onMenuPanelBeforeRender: function(component, eOpts) {

        console.log("权限管理开始..");
        Ext.Ajax.request({
            url: 'get_currentUserRight',
            success: function(response) {
                var result = JSON.parse(response.responseText);
                if (result.success) {
                    var rightMap = result.root;
                    var children = component.query('panel');
                    for (var index in children) {
                        var child = children[index];
                        if (child && child.xtype == 'panel') {
                            var title = child.title;
                            var isShow = rightMap[title];
                            if (!isShow || isShow=='undefined') {
                                child.setHidden(true);
                            }
                        }
                    }
                } else {
                    console.log("errorrr.");
                }
            },
            failure: function(conn, response, options, eOpts) {
                console.log("请求错误。");
            }
        });
    },

    onMainViewAfterRender: function(component, eOpts) {
        var xtype = 'homePanel';
        var mainView = Ext.getCmp('mainView');
        mainView.removeAll();
        mainView.add(Ext.widget(xtype));
    }

});