/*
 * File: app/view/notice_Publish.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.notice_Publish', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.notice_Publish',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.HtmlEditor',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden',
        'Ext.form.field.TextArea',
        'Ext.form.field.Display',
        'Ext.form.field.File',
        'Ext.button.Button'
    ],

    height: 588,
    width: 786,
    layout: 'fit',
    title: '内容发布',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            id: 'notice_PublishForm',
            bodyPadding: 20,
            jsonSubmit: true,
            method: 'POST',
            url: 'add_NoticeNews',
            items: [
                {
                    xtype: 'htmleditor',
                    anchor: '100% -85',
                    height: 300,
                    fieldLabel: '文章内容',
                    name: 'noticeContent'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'hidden',
                    name: 'id'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'hidden',
                    name: 'readCount'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'hidden',
                    name: 'publishDate'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    id: 'notice_publish_stateField',
                    fieldLabel: 'hidden',
                    name: 'noticeState',
                    value: 0
                },
                {
                    xtype: 'textareafield',
                    anchor: '100% 0',
                    height: 40,
                    maxHeight: 40,
                    fieldLabel: '备注',
                    name: 'description'
                },
                {
                    xtype: 'displayfield',
                    id: 'attachmentFilenameText',
                    margin: '',
                    width: 900,
                    fieldLabel: '附件',
                    name: 'attachmentFilename',
                    submitValue: true
                },
                {
                    xtype: 'hiddenfield',
                    id: 'attachmentFilepathText',
                    fieldLabel: 'hidden',
                    name: 'attachmentFilepath',
                    value: 342
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'tbfill',
                            fixed: true,
                            maxWidth: 5,
                            width: 10
                        },
                        {
                            xtype: 'textfield',
                            height: 30,
                            width: '50%',
                            fieldLabel: '  文章标题',
                            name: 'noticeTitle'
                        },
                        {
                            xtype: 'combobox',
                            width: 200,
                            fieldLabel: '栏目名称',
                            labelWidth: 60,
                            name: 'noticeColumn',
                            displayField: 'columnName',
                            forceSelection: true,
                            store: 'notice_columnsStore',
                            valueField: 'columnName'
                        },
                        {
                            xtype: 'combobox',
                            width: 180,
                            fieldLabel: '文章作者',
                            labelWidth: 60,
                            name: 'noticeAuthor',
                            displayField: 'trueName',
                            store: 'uUserInfoStore',
                            valueField: 'trueName'
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items: [
                {
                    xtype: 'form',
                    id: 'add_noticefileForm',
                    layout: 'table',
                    bodyPadding: 5,
                    items: [
                        {
                            xtype: 'filefield',
                            formBind: false,
                            margin: '0 0 0 5',
                            maxWidth: 300,
                            fieldLabel: '添加附件',
                            name: 'file',
                            buttonText: '打开',
                            listeners: {
                                afterrender: 'onFilefieldAfterRender1'
                            }
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                var myform = Ext.getCmp('add_noticefileForm').getForm();
                                if (myform.isValid())
                                {
                                    myform.submit({
                                        url : 'addNoticeNewsfile',
                                        method:'POST',
                                        success : function (form, action){
                                            var result=action.result;
                                            if(result.success=='true'||result.success===true){
                                                Ext.getCmp('attachmentFilepathText').setValue(result.filepath);
                                                Ext.getCmp('attachmentFilenameText').setValue(result.filenames);
                                                console.log(Ext.getCmp('attachmentFilepathText').value);
                                            }else{
                                                Ext.Msg.alert('失败', '文件存储失败，请重试。');
                                            }
                                        },
                                        failure: function(form, action){
                                            Ext.Msg.alert('失败', '文件上传失败，请重试。');
                                        }
                                    });
                                }
                                else
                                {
                                    Ext.Msg.alert('注意', '请先选择文件');
                                }
                            },
                            margin: '0 0 0 10',
                            text: '上传'
                        }
                    ]
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    handler: function() {
                        var myform = Ext.getCmp('notice_PublishForm').getForm();
                        if (myform.isValid())
                        {
                            Ext.getCmp('notice_publish_stateField').setValue('1');
                            myform.submit({
                                //url : 'add_NoticeNews',
                                success : function (form, action)
                                {
                                    Ext.Msg.alert('成功', '内容已存草稿箱。');
                                    var mystore = Ext.StoreMgr.get('notice_newsDraftStore'); //获得store对象
                                    mystore.reload();
                                    var publisStore = Ext.StoreMgr.get('notice_newsStore'); //获得store对象
                                    publisStore.reload();

                                    var xtype = 'notice_Management';
                                    var mainView = Ext.getCmp('mainView');
                                    mainView.removeAll();
                                    mainView.add(Ext.widget(xtype));
                                    Ext.getCmp('notice_table').setActiveTab(1);
                                },
                                failure: function(form, action){
                                    Ext.Msg.alert('失败', '内容存草稿箱失败，请重试。');
                                }
                            });
                        }
                        else
                        {
                            Ext.Msg.alert('注意', '填写的信息有误，请检查！');
                        }
                    },
                    text: '存草稿箱'
                },
                {
                    xtype: 'button',
                    handler: function() {
                        var myform = Ext.getCmp('notice_PublishForm').getForm();
                        if (myform.isValid())
                        {
                            Ext.getCmp('notice_publish_stateField').setValue('0');
                            myform.submit({
                                //url : 'add_NoticeNews',
                                success : function (form, action)
                                {
                                    Ext.Msg.alert('成功', '内容发布成功。');
                                    var mystore = Ext.StoreMgr.get('notice_newsStore'); //获得store对象
                                    mystore.reload();
                                    var draftStore = Ext.StoreMgr.get('notice_newsDraftStore'); //获得store对象
                                    draftStore.reload();


                                    var xtype = 'notice_Management';
                                    var mainView = Ext.getCmp('mainView');
                                    mainView.removeAll();
                                    mainView.add(Ext.widget(xtype));
                                },
                                failure: function(form, action){
                                    Ext.Msg.alert('失败', '内容发布失败，请重试。');
                                }
                            });
                        }
                        else
                        {
                            Ext.Msg.alert('注意', '填写的信息有误，请检查！');
                        }
                    },
                    text: '发布文章'
                }
            ]
        }
    ],

    onFilefieldAfterRender1: function(component, eOpts) {
                    component.fileInputEl.set({
                        multiple:'multiple'
                    });
    }

});